package com.kdrama.backend.controller;

import com.kdrama.backend.service.AiService;
import org.springframework.ai.document.Document;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;
import java.util.Map;

// Generated by GitHub Copilot

@RestController
@RequestMapping("/api/ai")
@CrossOrigin(origins = "*", maxAge = 3600)
public class AiController {

    @Autowired
    private final AiService aiService;
    
    public AiController(AiService aiService) {
        this.aiService = aiService;
    }

    /**
     * Generate a general response using Gemini
     */
    @PostMapping("/generate")
    public ResponseEntity<Map<String, String>> generateResponse(@RequestBody Map<String, String> request) {
        String prompt = request.get("prompt");
        if (prompt == null || prompt.isEmpty()) {
            return ResponseEntity.badRequest().body(Map.of("error", "Prompt is required"));
        }

        String response = aiService.generateResponse(prompt);
        return ResponseEntity.ok(Map.of("response", response));
    }

    /**
     * Generate drama recommendations
     */
    @PostMapping("/drama/recommendations")
    public ResponseEntity<Map<String, String>> getDramaRecommendations(@RequestBody Map<String, String> request) {
        String preferences = request.get("preferences");
        if (preferences == null || preferences.isEmpty()) {
            return ResponseEntity.badRequest().body(Map.of("error", "Preferences are required"));
        }

        String recommendations = aiService.generateDramaRecommendations(preferences);
        return ResponseEntity.ok(Map.of("recommendations", recommendations));
    }

    /**
     * Summarize drama information
     */
    @PostMapping("/drama/summarize")
    public ResponseEntity<Map<String, String>> summarizeDrama(@RequestBody Map<String, String> request) {
        String description = request.get("description");
        if (description == null || description.isEmpty()) {
            return ResponseEntity.badRequest().body(Map.of("error", "Description is required"));
        }

        String summary = aiService.summarizeDramaInfo(description);
        return ResponseEntity.ok(Map.of("summary", summary));
    }

    /**
     * Search similar documents in vector store
     */
    @GetMapping("/search")
    public ResponseEntity<List<Document>> searchDocuments(
            @RequestParam String query,
            @RequestParam(defaultValue = "5") int k) {
        List<Document> results = aiService.searchSimilarDocuments(query);
        return ResponseEntity.ok(results);
    }

    /**
     * Add documents to vector store
     */
    @PostMapping("/documents/add")
    public ResponseEntity<Map<String, String>> addDocuments(@RequestBody List<Map<String, String>> documentsData) {
        List<Document> documents = documentsData.stream()
                .map(doc -> new Document(doc.getOrDefault("content", "")))
                .toList();

        aiService.addDocuments(documents);
        return ResponseEntity.ok(Map.of("message", "Documents added successfully"));
    }
}
