package com.kdrama.backend.util;

import java.io.IOException;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.kdrama.backend.enums.HasDisplayName;

// Generated by ChatGPT
// To control whether loaded Json enum is displayed as name (e.g. MALE, FEMALE) or displayName (e.g. 男, 女)

public class DisplayNameEnumSerializer extends StdSerializer<Enum> {

    private boolean displayNameMode = true;

    public DisplayNameEnumSerializer() {
        super(Enum.class);
    }

    public DisplayNameEnumSerializer(boolean displayNameMode) {
        super(Enum.class);
        this.displayNameMode = displayNameMode;
    }

    @Override
    public void serialize(Enum value, JsonGenerator gen, SerializerProvider provider) throws IOException {
        if (displayNameMode && value instanceof HasDisplayName) {
            gen.writeString(((HasDisplayName) value).getDisplayName());
        } else {
            gen.writeString(value.name());
        }
    }
}
