package com.kdrama.backend.util;

import com.fasterxml.jackson.databind.JsonNode;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class DramaFilterUtil {
    // Most of the code is generated by ChatGPT

    // 正規韓國電視台
    private static final Set<String> BROADCAST_NETWORKS = new HashSet<>(Arrays.asList(
        "KBS2", "KBS1", "MBC", "SBS", "tvN", "JTBC", "OCN", "ENA", "TV Chosun", "MBN", "Channel A"
    ));

    // 正規韓國OTT平台 (90%以上都是正規劇)
    private static final Set<String> SEMI_OFFICIAL_STREAMING = new HashSet<>(Arrays.asList(
        "TVING", "Wavve", "Disney+", "U+ Mobile TV", "Netflix", "Coupang Play"
    ));


    public static boolean isValidKDrama(JsonNode dramaNode) {
        boolean foundBroadcast = false;
        boolean foundStreamingOfficial = false;

        JsonNode networks = dramaNode.path("networks");
        for (JsonNode network : networks) {
            String name = network.path("name").asText();
            if (BROADCAST_NETWORKS.contains(name)) {
                foundBroadcast = true;
            }
            if (SEMI_OFFICIAL_STREAMING.contains(name)) {
                foundStreamingOfficial = true;
            }
        }

        // 最終判斷邏輯
        return foundBroadcast || foundStreamingOfficial;
    }
}

