package com.kdrama.backend.service;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.model.ChatModel;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.chat.prompt.PromptTemplate;
import org.springframework.ai.document.Document;
import org.springframework.ai.embedding.EmbeddingModel;
import org.springframework.ai.vectorstore.pgvector.PgVectorStore;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import java.util.List;
import java.util.Map;

// Generated by GitHub Copilot

@Service
public class AiService {

    @Autowired
    private final ChatClient chatClient;
    private final EmbeddingModel embeddingModel;
    private final PgVectorStore vectorStore;

    public AiService(ChatModel chatModel, EmbeddingModel embeddingModel, PgVectorStore vectorStore) {
        this.chatClient = ChatClient.create(chatModel);
        this.embeddingModel = embeddingModel;
        this.vectorStore = vectorStore;
    }

    /**
     * Generate a simple response using Gemini
     */
    public String generateResponse(String prompt) {
        return chatClient.prompt()
                .user(prompt)
                .call()
                .content();
    }

    /**
     * Generate a response with a template and parameters
     */
    public String generateResponseWithTemplate(String templateText, Map<String, Object> params) {
        PromptTemplate promptTemplate = new PromptTemplate(templateText);
        Prompt prompt = promptTemplate.create(params);
        return chatClient.prompt(prompt)
                .call()
                .content();
    }

    /**
     * Add documents to the vector store for semantic search
     */
    public void addDocuments(List<Document> documents) {
        vectorStore.add(documents);
    }

    /**
     * Search for similar documents using vector similarity
     */
    public List<Document> searchSimilarDocuments(String query) {
        return vectorStore.similaritySearch(query);
    }

    /**
     * Generate drama recommendations using AI
     */
    public String generateDramaRecommendations(String userPreferences) {
        String template = """
                Based on the user's preferences: {userPreferences}
                Generate 5 K-drama recommendations with brief descriptions.
                Format the response as a numbered list.""";
        
        PromptTemplate promptTemplate = new PromptTemplate(template);
        Prompt prompt = promptTemplate.create(Map.of("userPreferences", userPreferences));
        
        return chatClient.prompt(prompt)
                .call()
                .content();
    }

    /**
     * Summarize drama information using AI
     */
    public String summarizeDramaInfo(String dramaDescription) {
        String template = """
                Summarize the following drama information in 2-3 sentences:
                {dramaDescription}""";
        
        PromptTemplate promptTemplate = new PromptTemplate(template);
        Prompt prompt = promptTemplate.create(Map.of("dramaDescription", dramaDescription));
        
        return chatClient.prompt(prompt)
                .call()
                .content();
    }
}
